import { Student } from "@/types/student";

export const mockStudents: Student[] = [
  {
    id: "1",
    studentId: "STU-001",
    firstName: "Aarav",
    lastName: "Patel",
    class: "9",
    section: "A",
    stream: "General",
    dateOfBirth: "2010-05-15",
    gender: "Male",
    contactNumber: "9876543210",
    parentName: "Rajesh Patel",
    parentContact: "9876543211",
    status: "Active",
  },
  {
    id: "2",
    studentId: "STU-002",
    firstName: "Vivaan",
    lastName: "Shah",
    class: "9",
    section: "B",
    stream: "General",
    dateOfBirth: "2010-02-20",
    gender: "Male",
    contactNumber: "9876543212",
    parentName: "Sanjay Shah",
    parentContact: "9876543213",
    status: "Active",
  },
  {
    id: "3",
    studentId: "STU-003",
    firstName: "Riya",
    lastName: "Patel",
    class: "10",
    section: "A",
    stream: "General",
    dateOfBirth: "2009-08-10",
    gender: "Female",
    contactNumber: "9876543214",
    parentName: "Amit Patel",
    parentContact: "9876543215",
    status: "Inactive",
  },
  {
    id: "4",
    studentId: "STU-004",
    firstName: "Diya",
    lastName: "Mehta",
    class: "10",
    section: "C",
    stream: "General",
    dateOfBirth: "2009-11-05",
    gender: "Female",
    contactNumber: "9876543216",
    parentName: "Manoj Mehta",
    parentContact: "9876543217",
    status: "Active",
  },
  {
    id: "5",
    studentId: "STU-005",
    firstName: "Krish",
    lastName: "Patel",
    class: "11",
    section: "A",
    stream: "Science",
    dateOfBirth: "2008-03-25",
    gender: "Male",
    contactNumber: "9876543218",
    parentName: "Vijay Patel",
    parentContact: "9876543219",
    status: "Active",
  },
  {
    id: "6",
    studentId: "STU-006",
    firstName: "Arjun",
    lastName: "Kumar",
    class: "11",
    section: "B",
    stream: "Science",
    dateOfBirth: "2008-07-12",
    gender: "Male",
    contactNumber: "9876543220",
    parentName: "Sunil Kumar",
    parentContact: "9876543221",
    status: "Active",
  },
  {
    id: "7",
    studentId: "STU-007",
    firstName: "Ananya",
    lastName: "Singh",
    class: "11",
    section: "C",
    stream: "Commerce",
    dateOfBirth: "2008-09-30",
    gender: "Female",
    contactNumber: "9876543222",
    parentName: "Ravi Singh",
    parentContact: "9876543223",
    status: "Active",
  },
  {
    id: "8",
    studentId: "STU-008",
    firstName: "Aditya",
    lastName: "Sharma",
    class: "11",
    section: "D",
    stream: "Commerce",
    dateOfBirth: "2008-01-18",
    gender: "Male",
    contactNumber: "9876543224",
    parentName: "Rajeev Sharma",
    parentContact: "9876543225",
    status: "Inactive",
  },
  {
    id: "9",
    studentId: "STU-009",
    firstName: "Ishita",
    lastName: "Gupta",
    class: "12",
    section: "A",
    stream: "Science",
    dateOfBirth: "2007-12-22",
    gender: "Female",
    contactNumber: "9876543226",
    parentName: "Prakash Gupta",
    parentContact: "9876543227",
    status: "Active",
  },
  {
    id: "10",
    studentId: "STU-010",
    firstName: "Rahul",
    lastName: "Verma",
    class: "12",
    section: "B",
    stream: "Science",
    dateOfBirth: "2007-04-05",
    gender: "Male",
    contactNumber: "9876543228",
    parentName: "Anil Verma",
    parentContact: "9876543229",
    status: "Active",
  },
  {
    id: "11",
    studentId: "STU-011",
    firstName: "Neha",
    lastName: "Reddy",
    class: "12",
    section: "C",
    stream: "Commerce",
    dateOfBirth: "2007-06-15",
    gender: "Female",
    contactNumber: "9876543230",
    parentName: "Srinivas Reddy",
    parentContact: "9876543231",
    status: "Active",
  },
  {
    id: "12",
    studentId: "STU-012",
    firstName: "Karan",
    lastName: "Joshi",
    class: "12",
    section: "D",
    stream: "Commerce",
    dateOfBirth: "2007-10-10",
    gender: "Male",
    contactNumber: "9876543232",
    parentName: "Dilip Joshi",
    parentContact: "9876543233",
    status: "Active",
  },
];

import { Teacher } from "@/types/teacher";

export const mockTeachers: Teacher[] = [
  {
    id: "1",
    teacherId: "TCH-101",
    firstName: "Ramesh",
    lastName: "Iyer",
    email: "ramesh.iyer@edusphere.example.com",
    contactNumber: "9876500001",
    primarySubject: "Mathematics",
    additionalSubject: "Physics",
    qualification: "M.Sc. Mathematics, B.Ed.",
    joiningDate: "2015-06-01",
    status: "Active",
    assignedClasses: ["Class 10", "Class 11 Science", "Class 12 Science"],
  },
  {
    id: "2",
    teacherId: "TCH-102",
    firstName: "Priya",
    lastName: "Desai",
    email: "priya.desai@edusphere.example.com",
    contactNumber: "9876500002",
    primarySubject: "English",
    qualification: "M.A. English, B.Ed.",
    joiningDate: "2018-04-15",
    status: "Active",
    assignedClasses: ["Class 9", "Class 10", "Class 11 Commerce"],
  },
  {
    id: "3",
    teacherId: "TCH-103",
    firstName: "Suresh",
    lastName: "Nair",
    email: "suresh.nair@edusphere.example.com",
    contactNumber: "9876500003",
    primarySubject: "Physics",
    qualification: "M.Sc. Physics, M.Ed.",
    joiningDate: "2012-07-10",
    status: "Active",
    assignedClasses: ["Class 11 Science", "Class 12 Science"],
  },
  {
    id: "4",
    teacherId: "TCH-104",
    firstName: "Meera",
    lastName: "Reddy",
    email: "meera.reddy@edusphere.example.com",
    contactNumber: "9876500004",
    primarySubject: "Chemistry",
    additionalSubject: "Biology",
    qualification: "M.Sc. Chemistry, B.Ed.",
    joiningDate: "2019-06-20",
    status: "On Leave",
    assignedClasses: ["Class 11 Science", "Class 12 Science"],
  },
  {
    id: "5",
    teacherId: "TCH-105",
    firstName: "Amit",
    lastName: "Bansal",
    email: "amit.bansal@edusphere.example.com",
    contactNumber: "9876500005",
    primarySubject: "Accountancy",
    additionalSubject: "Business Studies",
    qualification: "M.Com, B.Ed.",
    joiningDate: "2016-08-05",
    status: "Active",
    assignedClasses: ["Class 11 Commerce", "Class 12 Commerce"],
  },
  {
    id: "6",
    teacherId: "TCH-106",
    firstName: "Kavita",
    lastName: "Joshi",
    email: "kavita.joshi@edusphere.example.com",
    contactNumber: "9876500006",
    primarySubject: "Economics",
    qualification: "M.A. Economics, B.Ed.",
    joiningDate: "2020-03-12",
    status: "Active",
    assignedClasses: ["Class 9", "Class 10", "Class 11 Commerce", "Class 12 Commerce"],
  },
  {
    id: "7",
    teacherId: "TCH-107",
    firstName: "Rajeev",
    lastName: "Verma",
    email: "rajeev.verma@edusphere.example.com",
    contactNumber: "9876500007",
    primarySubject: "Computer Science",
    qualification: "M.C.A., B.Ed.",
    joiningDate: "2017-11-25",
    status: "Active",
    assignedClasses: ["Class 9", "Class 10", "Class 11 Science", "Class 12 Science"],
  },
  {
    id: "8",
    teacherId: "TCH-108",
    firstName: "Sneha",
    lastName: "Kapur",
    email: "sneha.kapur@edusphere.example.com",
    contactNumber: "9876500008",
    primarySubject: "Biology",
    qualification: "M.Sc. Biology, B.Ed.",
    joiningDate: "2021-01-10",
    status: "Active",
    assignedClasses: ["Class 9", "Class 10", "Class 11 Science"],
  },
  {
    id: "9",
    teacherId: "TCH-109",
    firstName: "Vikram",
    lastName: "Singh",
    email: "vikram.singh@edusphere.example.com",
    contactNumber: "9876500009",
    primarySubject: "Mathematics",
    qualification: "M.Sc. Mathematics, B.Ed.",
    joiningDate: "2014-09-18",
    status: "Inactive",
    assignedClasses: ["Class 9", "Class 10"],
  },
  {
    id: "10",
    teacherId: "TCH-110",
    firstName: "Anjali",
    lastName: "Mehta",
    email: "anjali.mehta@edusphere.example.com",
    contactNumber: "9876500010",
    primarySubject: "Gujarati",
    qualification: "M.A. Gujarati, B.Ed.",
    joiningDate: "2013-05-22",
    status: "Active",
    assignedClasses: ["Class 9", "Class 10", "Class 11 Science", "Class 11 Commerce"],
  },
];

import { SchoolClass } from "@/types/schoolClass";

export const mockClasses: SchoolClass[] = [
  {
    id: "class-9-general",
    classLevel: "9",
    stream: "General",
    totalStudents: 100,
    sections: [
      { id: "sec-9-a", name: "Section A", studentCount: 50, classTeacher: "Priya Desai" },
      { id: "sec-9-b", name: "Section B", studentCount: 50, classTeacher: "Kavita Joshi" },
    ],
  },
  {
    id: "class-10-general",
    classLevel: "10",
    stream: "General",
    totalStudents: 95,
    sections: [
      { id: "sec-10-a", name: "Section A", studentCount: 48, classTeacher: "Ramesh Iyer" },
      { id: "sec-10-b", name: "Section B", studentCount: 47, classTeacher: "Anjali Mehta" },
    ],
  },
  {
    id: "class-11-science",
    classLevel: "11",
    stream: "Science",
    totalStudents: 95,
    sections: [
      { id: "sec-11-sci-a", name: "Section A", studentCount: 48, classTeacher: "Suresh Nair" },
      { id: "sec-11-sci-b", name: "Section B", studentCount: 47, classTeacher: "Meera Reddy" },
    ],
  },
  {
    id: "class-11-commerce",
    classLevel: "11",
    stream: "Commerce",
    totalStudents: 50,
    sections: [
      { id: "sec-11-com-a", name: "Section A", studentCount: 50, classTeacher: "Amit Bansal" },
    ],
  },
  {
    id: "class-12-science",
    classLevel: "12",
    stream: "Science",
    totalStudents: 90,
    sections: [
      { id: "sec-12-sci-a", name: "Section A", studentCount: 45, classTeacher: "Rajeev Verma" },
      { id: "sec-12-sci-b", name: "Section B", studentCount: 45, classTeacher: "Sneha Kapur" },
    ],
  },
  {
    id: "class-12-commerce",
    classLevel: "12",
    stream: "Commerce",
    totalStudents: 45,
    sections: [
      { id: "sec-12-com-a", name: "Section A", studentCount: 45, classTeacher: "Kavita Joshi" },
    ],
  },
];
