import { Student } from "@/types/student";

export const mockStudents: Student[] = [
  {
    id: "1",
    studentId: "STU-001",
    firstName: "Alice",
    lastName: "Johnson",
    class: "10",
    section: "A",
    dateOfBirth: "2010-05-15",
    gender: "Female",
    contactNumber: "555-0101",
    parentName: "Robert Johnson",
    parentContact: "555-0102",
    status: "Active",
  },
  {
    id: "2",
    studentId: "STU-002",
    firstName: "Michael",
    lastName: "Smith",
    class: "10",
    section: "B",
    dateOfBirth: "2010-02-20",
    gender: "Male",
    contactNumber: "555-0201",
    parentName: "Sarah Smith",
    parentContact: "555-0202",
    status: "Active",
  },
  {
    id: "3",
    studentId: "STU-003",
    firstName: "Emma",
    lastName: "Davis",
    class: "9",
    section: "A",
    dateOfBirth: "2011-08-10",
    gender: "Female",
    contactNumber: "555-0301",
    parentName: "John Davis",
    parentContact: "555-0302",
    status: "Inactive",
  },
  {
    id: "4",
    studentId: "STU-004",
    firstName: "James",
    lastName: "Wilson",
    class: "11",
    section: "C",
    dateOfBirth: "2009-11-05",
    gender: "Male",
    contactNumber: "555-0401",
    parentName: "Mary Wilson",
    parentContact: "555-0402",
    status: "Active",
  },
  {
    id: "5",
    studentId: "STU-005",
    firstName: "Sophia",
    lastName: "Brown",
    class: "9",
    section: "B",
    dateOfBirth: "2011-03-25",
    gender: "Female",
    contactNumber: "555-0501",
    parentName: "David Brown",
    parentContact: "555-0502",
    status: "Active",
  },
  {
    id: "6",
    studentId: "STU-006",
    firstName: "William",
    lastName: "Taylor",
    class: "12",
    section: "A",
    dateOfBirth: "2008-07-12",
    gender: "Male",
    contactNumber: "555-0601",
    parentName: "Jennifer Taylor",
    parentContact: "555-0602",
    status: "Active",
  },
  {
    id: "7",
    studentId: "STU-007",
    firstName: "Olivia",
    lastName: "Anderson",
    class: "10",
    section: "C",
    dateOfBirth: "2010-09-30",
    gender: "Female",
    contactNumber: "555-0701",
    parentName: "Richard Anderson",
    parentContact: "555-0702",
    status: "Active",
  },
  {
    id: "8",
    studentId: "STU-008",
    firstName: "Alexander",
    lastName: "Thomas",
    class: "8",
    section: "A",
    dateOfBirth: "2012-01-18",
    gender: "Male",
    contactNumber: "555-0801",
    parentName: "Lisa Thomas",
    parentContact: "555-0802",
    status: "Inactive",
  },
  {
    id: "9",
    studentId: "STU-009",
    firstName: "Isabella",
    lastName: "Jackson",
    class: "11",
    section: "B",
    dateOfBirth: "2009-12-22",
    gender: "Female",
    contactNumber: "555-0901",
    parentName: "Christopher Jackson",
    parentContact: "555-0902",
    status: "Active",
  },
  {
    id: "10",
    studentId: "STU-010",
    firstName: "Ethan",
    lastName: "White",
    class: "12",
    section: "B",
    dateOfBirth: "2008-04-05",
    gender: "Male",
    contactNumber: "555-1001",
    parentName: "Patricia White",
    parentContact: "555-1002",
    status: "Active",
  },
];
